name: 'Local Action'
description: 'Runs a composite step action'
inputs:
  name:
    required: false
    description: "Name"

outputs:
  random:
    description: "Random number output"
    value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
   - run: echo Hello ${{ inputs.name }}.
     shell: bash
