name: 'Local Action'
description: 'Runs a composite step action'
inputs:
  name:
    required: false
    description: "Name"

outputs:
  random:
    description: "Random number output"
    value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
   - run: echo Hello ${{ inputs.name }}.
     shell: bash
   - name: Configure AWS credentialsa
     uses: aws-actions/configure-aws-credentials@v4 
     with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          # role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}